"""System and user prompts."""

from .intent_interpreter_prompts import (
    INTENT_INTERPRETER_CREATE_SYSTEM_PROMPT,
    INTENT_INTERPRETER_MODIFY_SYSTEM_PROMPT,
    INTENT_INTERPRETER_CREATE_PROMPT,
    INTENT_INTERPRETER_MODIFY_PROMPT,
)
from .architect_prompts import (
    ARCHITECT_INITIAL_SYSTEM_PROMPT,
    ARCHITECT_ITERATIVE_SYSTEM_PROMPT,
    ARCHITECT_INITIAL_PROMPT,
    ARCHITECT_ITERATIVE_PROMPT,
)
from .spec_planner_prompts import (
    SPEC_PLANNER_SYSTEM_PROMPT,
    SPEC_PLANNER_PROMPT,
)
from .code_agents import (
    BACKEND_MODEL_AGENT_SYSTEM_PROMPT,
    BACKEND_MODEL_AGENT_PROMPT,
)

__all__ = [
    "INTENT_INTERPRETER_CREATE_SYSTEM_PROMPT",
    "INTENT_INTERPRETER_MODIFY_SYSTEM_PROMPT",
    "INTENT_INTERPRETER_CREATE_PROMPT",
    "INTENT_INTERPRETER_MODIFY_PROMPT",
    "ARCHITECT_INITIAL_SYSTEM_PROMPT",
    "ARCHITECT_ITERATIVE_SYSTEM_PROMPT",
    "ARCHITECT_INITIAL_PROMPT",
    "ARCHITECT_ITERATIVE_PROMPT",
    "SPEC_PLANNER_SYSTEM_PROMPT",
    "SPEC_PLANNER_PROMPT",
    "BACKEND_MODEL_AGENT_SYSTEM_PROMPT",
    "BACKEND_MODEL_AGENT_PROMPT",
]

