"""System and user prompts."""

from .intent_interpreter_prompts import (
    INTENT_INTERPRETER_CREATE_SYSTEM_PROMPT,
    INTENT_INTERPRETER_MODIFY_SYSTEM_PROMPT,
    INTENT_INTERPRETER_CREATE_PROMPT,
    INTENT_INTERPRETER_MODIFY_PROMPT,
)
from .architect_prompts import (
    ARCHITECT_INITIAL_SYSTEM_PROMPT,
    ARCHITECT_ITERATIVE_SYSTEM_PROMPT,
    ARCHITECT_INITIAL_PROMPT,
    ARCHITECT_ITERATIVE_PROMPT,
)

__all__ = [
    "INTENT_INTERPRETER_CREATE_SYSTEM_PROMPT",
    "INTENT_INTERPRETER_MODIFY_SYSTEM_PROMPT",
    "INTENT_INTERPRETER_CREATE_PROMPT",
    "INTENT_INTERPRETER_MODIFY_PROMPT",
    "ARCHITECT_INITIAL_SYSTEM_PROMPT",
    "ARCHITECT_ITERATIVE_SYSTEM_PROMPT",
    "ARCHITECT_INITIAL_PROMPT",
    "ARCHITECT_ITERATIVE_PROMPT",
]

