"""Shared models and TypedDicts for Code Generation Agents."""

from typing import TypedDict, List, Dict, Any
from pydantic import BaseModel, Field


class CodeAgentResult(TypedDict):
    """Standard result contract for all code generation agents.
    
    Every coding agent must return this structure to enable:
    - code_map.json generation
    - Deterministic retries
    - Selective regeneration
    """
    generated_files: List[str]  # List of file paths relative to app root (e.g., ["backend/models/task.py"])
    warnings: List[str]  # List of warning messages (e.g., ["Model X uses deprecated field Y"])
    metadata: Dict[str, Any]  # Additional metadata (e.g., {"models_created": 3, "total_lines": 150})


class GeneratedFile(BaseModel):
    """Represents a single generated code file."""
    filename: str = Field(
        ...,
        description="The filename of the generated file (e.g., 'task.py', 'user.py') - use snake_case naming"
    )
    code_content: str = Field(
        ...,
        description=(
            "The complete Python code content for this file as a string. "
            "Must include: proper imports (BaseModel, Field, ConfigDict, typing), "
            "model classes with detailed Field descriptions, "
            "and model_config = ConfigDict(extra='forbid') for Create/Update models. "
            "Do NOT include id fields or non-functional metadata like read_only=True."
        )
    )
    imports: List[str] = Field(
        default_factory=list,
        description="List of symbols imported from OTHER PROJECT FILES (e.g., ['TaskCreate', 'TaskUpdate']). Do NOT include external library imports here - those go in dependencies. These must also appear in the file's import statements."
    )
    exports: List[str] = Field(
        default_factory=list,
        description="List of symbols defined in this file that other files can import (e.g., ['Task', 'TaskCreate', 'TaskUpdate'])."
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of external Python packages needed to run this file (e.g., ['pydantic', 'fastapi']). Only include third-party libraries, NOT standard library modules or internal project files."
    )
    summary: str = Field(
        ...,
        description=(
            "Brief summary of the file's role and functionality. Include: "
            "main purpose, key functions/classes defined, their responsibilities, "
            "critical parameters/arguments, and return types. Keep it concise "
            "but informative enough for other agents to understand how to use this module."
        )
    )


class ManifestFile(BaseModel):

    file_path: str = Field(
        ...,
        description="The path to the file relative to the app root."
    )
    imports: List[str] = Field(
        default_factory=list,
        description="List of symbols imported from OTHER PROJECT FILES (e.g., ['TaskCreate', 'TaskUpdate']). Do NOT include external library imports here - those go in dependencies. These must also appear in the file's import statements."
    )
    exports: List[str] = Field(
        default_factory=list,
        description="List of symbols defined in this file that other files can import (e.g., ['Task', 'TaskCreate', 'TaskUpdate'])."
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of external Python packages needed to run this file (e.g., ['pydantic', 'fastapi']). Only include third-party libraries, NOT standard library modules or internal project files."
    )
    summary: str = Field(
        ...,
        description=(
            "Brief summary of the file's role and functionality. Include: "
            "main purpose, key functions/classes defined, their responsibilities, "
            "critical parameters/arguments, and return types. Keep it concise "
            "but informative enough for other agents to understand how to use this module."
        )
    )

class Manifest(BaseModel):

    layer_id: str = Field(
        ...,
        description="The ID of the layer that generated this manifest."
    )
    spec: Dict[str, Any] = Field(
        ...,
        description="The spec of the layer."
    )
    manifest_files: List[ManifestFile] = Field(
        ...,
        description="The list of files generated by the layer."
    )

class Manifests(BaseModel):
    manifests: List[Manifest] = Field(
        ...,
        description="The list of manifests."
    )
    