"""Pydantic models for Spec Planner Agent."""

from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Literal


class ModelField(BaseModel):
    """Field definition for a model."""
    name: str = Field(description="Field name")
    type: str = Field(description="Python type (e.g., 'str', 'int', 'bool', 'datetime')")
    required: bool = Field(default=True, description="Whether this field is required")
    read_only: bool = Field(
        default=False,
        description="Whether this field is read-only (e.g., 'id' field in domain models). Read-only fields are generated by the system, not provided by users."
    )


class ModelDefinition(BaseModel):
    """Model definition for backend models layer."""
    name: str = Field(description="Model name (e.g., 'Task', 'TaskCreate', 'TaskUpdate')")
    type: Literal["pydantic"] = Field(default="pydantic", description="Model type")
    purpose: str = Field(description="Model purpose: 'domain' for main entity with id, 'create' for creation payload, 'update' for update payload")
    fields: List[ModelField] = Field(description="List of field definitions")


class BackendModelsSpec(BaseModel):
    """Specification for backend models layer."""
    models: List[ModelDefinition] = Field(
        description="List of model definitions. Must include domain model (with id), create model (without id), and update model (optional fields) for each entity."
    )


class DatabaseTableColumn(BaseModel):
    """Column definition for a database table."""
    name: str = Field(description="Column name")
    type: str = Field(description="SQLite type (e.g., 'TEXT', 'INTEGER', 'REAL', 'BLOB')")
    primary_key: bool = Field(default=False, description="Whether this is a primary key")
    nullable: bool = Field(default=True, description="Whether this column can be NULL")
    generation: Optional[Literal["auto_increment", "uuid", "manual"]] = Field(
        default=None, 
        description="How this column's value is generated. Required for primary key columns. 'auto_increment' for database-generated sequential IDs, 'uuid' for UUID generation, 'manual' for client-provided values."
    )


class DatabaseTable(BaseModel):
    """Table definition for database layer."""
    entity: str = Field(description="Entity name this table represents")
    table_name: str = Field(description="SQL table name")
    columns: List[DatabaseTableColumn] = Field(description="List of column definitions including id column")


class RepositoryMethod(BaseModel):
    """Repository method definition."""
    name: str = Field(description="Method name (e.g., 'create_task', 'get_task_by_id', 'list_tasks', 'update_task', 'delete_task')")
    operation: Literal["create", "read", "update", "delete"] = Field(description="CRUD operation type")
    inputs: List[str] = Field(
        default_factory=list,
        description="Input parameter types in order (e.g., ['int', 'TaskUpdate'] for update_task). Use model names for entities, basic types for IDs."
    )
    returns: str = Field(
        description="Return type (e.g., 'Task', 'List[Task]', 'None', 'Optional[Task]')"
    )


class EntityRepository(BaseModel):
    """Repository definition for an entity."""
    entity: str = Field(description="Entity name this repository serves")
    methods: List[RepositoryMethod] = Field(description="Data access methods for this entity")


class DatabaseSpec(BaseModel):
    """Specification for database layer."""
    tables: List[DatabaseTable] = Field(description="List of table definitions")
    repositories: List[EntityRepository] = Field(description="Repository definitions with explicit data access methods")


class ServiceFunction(BaseModel):
    """Function definition for a service."""
    name: str = Field(description="Function name (e.g., 'create_task', 'get_tasks')")
    inputs: List[str] = Field(description="List of input parameter types (e.g., ['TaskCreate'], [])")
    returns: str = Field(description="Return type (e.g., 'Task', 'List[Task]', 'None')")
    operation: Literal["create", "read", "update", "delete"] = Field(
        description="CRUD operation this function implements"
    )


class EntityService(BaseModel):
    """Service definition for an entity."""
    entity: str = Field(description="Entity name this service handles")
    functions: List[ServiceFunction] = Field(description="List of service functions")


class BackendServicesSpec(BaseModel):
    """Specification for backend services layer."""
    services: List[EntityService] = Field(description="List of entity service definitions")


class RouteDefinition(BaseModel):
    """Route definition for backend routes layer."""
    method: Literal["GET", "POST", "PUT", "DELETE", "PATCH"] = Field(description="HTTP method")
    path: str = Field(description="URL path (e.g., '/tasks', '/tasks/{id}')")
    service_call: str = Field(description="Service function to call (e.g., 'TaskService.create_task')")
    entity: str = Field(description="Entity this route operates on")
    request_model: Optional[str] = Field(
        default=None,
        description="Model type for request body (e.g., 'TaskCreate', 'TaskUpdate'). Required for POST, PUT, PATCH. None for GET, DELETE."
    )
    response_model: str = Field(
        description="Model type for response (e.g., 'Task', 'List[Task]'). Use 'None' for DELETE operations."
    )


class BackendRoutesSpec(BaseModel):
    """Specification for backend routes layer."""
    routes: List[RouteDefinition] = Field(description="List of route definitions")


class BackendAppBootstrapSpec(BaseModel):
    """Specification for backend app bootstrap layer."""
    app_type: Literal["fastapi"] = Field(description="Application framework type")
    routers: List[str] = Field(description="List of router module names to register")
    middleware: List[str] = Field(default_factory=list, description="List of middleware to configure")


class APIEndpoint(BaseModel):
    """API endpoint definition."""
    method: str = Field(description="HTTP method (GET, POST, PUT, DELETE, etc.)")
    path: str = Field(description="URL path (e.g., '/tasks', '/tasks/{id}')")


class FormDefinition(BaseModel):
    """Form field definition for a view."""
    view_type: Literal["create", "edit"] = Field(description="Which view this form is for")
    fields: List[str] = Field(description="List of entity field names to include in this form (e.g., ['title', 'description'])")


class PageView(BaseModel):
    """View definition for a page."""
    entity: str = Field(description="Entity this view handles")
    views: List[Literal["list", "create", "edit", "detail", "delete", "dashboard"]] = Field(
        description="List of view types to implement"
    )
    forms: List[FormDefinition] = Field(
        description="Form field definitions for create/edit views. Specifies which entity fields appear in each form."
    )
    api_endpoints: List[APIEndpoint] = Field(
        description="List of API endpoints to consume"
    )


class FrontendUISpec(BaseModel):
    """Specification for frontend UI layer."""
    pages: List[PageView] = Field(description="List of page/view definitions")


